// <auto-generated />
using System;
using Architecture.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Architecture.Domain.Migrations
{
    [DbContext(typeof(SaleDBContext))]
    partial class SaleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Architecture.Domain.SaleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssetName")
                        .HasMaxLength(50);

                    b.Property<DateTime>("EndSale");

                    b.Property<string>("PublisherEmail");

                    b.Property<DateTime>("StartSale");

                    b.HasKey("Id");

                    b.ToTable("SaleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
